spring:
  security:
    user:
      name: alvin
      password: 123456
      roles: admin
  datasource:
    url: jdbc:mysql://localhost:3306/security_table?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  typeAliasesPackage: org.alvin.pojo
  mapperLocations: classpath:mapper/*.xml